[package]
name = "nova-core"
version.workspace = true
edition.workspace = true
license.workspace = true
description = "Core utilities for Nova Physics Engine"

[dependencies]
nova-math.workspace = true
slotmap.workspace = true
smallvec.workspace = true
parking_lot.workspace = true
